defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: "123456"
  pool: 12

development:
  <<: *defaults
  database: free_project_development

production:
  <<: *defaults
  database: free_project_production

test: &test
  <<: *defaults
  database: free_project_test